# Generated by Django 5.0 on 2023-12-16 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeDTR.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeDTR.position'),
        ),
    ]
