# Generated by Django 5.0 on 2023-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0002_remove_department_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('P', 'Part-Time'), ('F', 'Full-Time'), ('Flex', 'Flex-Time')], default='P', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(1, 0)]),
        ),
    ]
