# Generated by Django 5.0 on 2023-12-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0003_remove_employee_password_employee_employee_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('Party-Time', 'Part-Time'), ('Full-Time', 'Full-Time'), ('Flex', 'Flex-Time'), ('Project-Based', 'Project-Based')], default='P', max_length=100),
        ),
    ]
