# Generated by Django 5.0 on 2023-12-16 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0006_alter_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeIn_AM', models.TimeField()),
                ('timeOut_AM', models.TimeField()),
                ('timeIn_PM', models.TimeField()),
                ('timeOut_PM', models.TimeField()),
                ('overtimeIn', models.TimeField()),
                ('overtimeOut', models.TimeField()),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeDTR.employee')),
            ],
        ),
    ]
