# Generated by Django 4.2 on 2023-12-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0007_dtr'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtr',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time'), ('Flex-Time', 'Flex-Time'), ('Project-Based', 'Project-Based')], default='Part-Time', max_length=100),
        ),
    ]
