# Generated by Django 4.2 on 2023-12-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0008_dtr_paid_alter_employee_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoansTaxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeDTR.employee')),
                ('loanTaxes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeDTR.loanstaxes')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='loan_taxes',
            field=models.ManyToManyField(through='employeeDTR.Deductions', to='employeeDTR.loanstaxes'),
        ),
    ]
