# Generated by Django 4.2 on 2023-12-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0009_loanstaxes_deductions_employee_loan_taxes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='loan_taxes',
            new_name='Loan_Taxes',
        ),
    ]
