# Generated by Django 4.2 on 2023-12-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0010_rename_loan_taxes_employee_loan_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Loan_Taxes',
            field=models.ManyToManyField(related_name='employee', through='employeeDTR.Deductions', to='employeeDTR.loanstaxes'),
        ),
    ]
