# Generated by Django 4.2 on 2023-12-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0011_alter_employee_loan_taxes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Loan_Taxes',
            new_name='sample_loans',
        ),
    ]
