# Generated by Django 4.2 on 2023-12-19 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0012_rename_loan_taxes_employee_sample_loans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_regular_hours', models.FloatField()),
                ('total_overtime_hours', models.FloatField()),
                ('total_deductions', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeDTR.employee')),
            ],
        ),
    ]
