# Generated by Django 4.2 on 2023-12-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0013_payroll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
