# Generated by Django 4.2 on 2024-01-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0015_employee_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
