# Generated by Django 5.0.3 on 2024-03-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0016_employee_password_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
    ]
