# Generated by Django 5.0.3 on 2024-03-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0018_rename_overtimein_dtr_overtime_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtr',
            name='overtime_in',
        ),
        migrations.RemoveField(
            model_name='dtr',
            name='overtime_out',
        ),
        migrations.RemoveField(
            model_name='dtr',
            name='paid',
        ),
    ]
