# Generated by Django 5.0.3 on 2024-03-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0019_remove_dtr_overtime_in_remove_dtr_overtime_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtr',
            name='id_number',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dtr',
            name='location_id',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dtr',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dtr',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
