# Generated by Django 5.0.3 on 2024-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0020_alter_dtr_id_number_alter_dtr_location_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtr',
            name='id_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
