# Generated by Django 5.0.3 on 2024-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDTR', '0024_employee_overtime_rate_alter_dtr_location_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightDifferential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('rate_multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
